// Generated by gencpp from file traffic_light/msg_traffic_light.msg
// DO NOT EDIT!


#ifndef TRAFFIC_LIGHT_MESSAGE_MSG_TRAFFIC_LIGHT_H
#define TRAFFIC_LIGHT_MESSAGE_MSG_TRAFFIC_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace traffic_light
{
template <class ContainerAllocator>
struct msg_traffic_light_
{
  typedef msg_traffic_light_<ContainerAllocator> Type;

  msg_traffic_light_()
    : header()
    , color(0)
    , left(false)
    , forward(false)
    , right(false)  {
    }
  msg_traffic_light_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , color(0)
    , left(false)
    , forward(false)
    , right(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _color_type;
  _color_type color;

   typedef uint8_t _left_type;
  _left_type left;

   typedef uint8_t _forward_type;
  _forward_type forward;

   typedef uint8_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::traffic_light::msg_traffic_light_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_light::msg_traffic_light_<ContainerAllocator> const> ConstPtr;

}; // struct msg_traffic_light_

typedef ::traffic_light::msg_traffic_light_<std::allocator<void> > msg_traffic_light;

typedef boost::shared_ptr< ::traffic_light::msg_traffic_light > msg_traffic_lightPtr;
typedef boost::shared_ptr< ::traffic_light::msg_traffic_light const> msg_traffic_lightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_light::msg_traffic_light_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_light::msg_traffic_light_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace traffic_light

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'traffic_light': ['/media/yarten/DATA/Project/ROS/Parallel/src/traffic_light/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light::msg_traffic_light_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light::msg_traffic_light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light::msg_traffic_light_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dd80e864b9d32350f10a9fd1e00a1c5";
  }

  static const char* value(const ::traffic_light::msg_traffic_light_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dd80e864b9d3235ULL;
  static const uint64_t static_value2 = 0x0f10a9fd1e00a1c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_light/msg_traffic_light";
  }

  static const char* value(const ::traffic_light::msg_traffic_light_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 color\n\
bool left\n\
bool forward\n\
bool right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::traffic_light::msg_traffic_light_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.color);
      stream.next(m.left);
      stream.next(m.forward);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_traffic_light_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_light::msg_traffic_light_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traffic_light::msg_traffic_light_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
    s << indent << "left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left);
    s << indent << "forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward);
    s << indent << "right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_LIGHT_MESSAGE_MSG_TRAFFIC_LIGHT_H
